import { ProviderConfig } from "./types"

export const PROVIDERS: Record<string, ProviderConfig[]> = {
  nano: [
    ...Array.from({ length: 4 }, (_, i) => ({
      id: `gemini-flash-nano-${i + 1}`,
      name: "Gemini Flash",
      endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:streamGenerateContent",
      apiKey: process.env[`GEMINI_FLASH_KEY_${i + 1}`]?.startsWith('your-') ? (process.env.GEMINI_KEY || process.env.GOOGLE_GENERATIVE_AI_API_KEY)! : process.env[`GEMINI_FLASH_KEY_${i + 1}`]!,
      model: "gemini-1.5-flash",
      tier: "nano" as const,
      maxTokens: 2048,
      supportsVision: true,
      supportsStreaming: true,
      rateLimit: 60,
      priority: i + 1,
    })),
    {
      id: "cerebras-nano",
      name: "Cerebras",
      endpoint: "https://api.cerebras.ai/v1/chat/completions",
      apiKey: process.env.CEREBRAS_KEY!,
      model: "llama-3.3-70b",
      tier: "nano",
      maxTokens: 2048,
      supportsVision: false,
      supportsStreaming: true,
      rateLimit: 30,
      priority: 2,
    },
  ],
  prime: [
    // SiliconFlow keys 1-6 rotated
    ...Array.from({ length: 6 }, (_, i) => ({
      id: `siliconflow-prime-${i + 1}`,
      name: "SiliconFlow Prime",
      endpoint: "https://api.siliconflow.cn/v1/chat/completions",
      apiKey: process.env[`SILICONFLOW_KEY_${i + 1}`]!,
      model: "Qwen/Qwen2.5-7B-Instruct", // Using 7B for Prime
      tier: "prime" as const,
      maxTokens: 4096,
      supportsVision: false,
      supportsStreaming: true,
      rateLimit: 100,
      priority: i + 1,
    })),
    // Dynamic HF Space mapping — router.ts will resolve the endpoint at runtime using current active space
    {
      id: "hf-prime-dynamic",
      name: "HF Prime",
      endpoint: "dynamic", 
      apiKey: process.env.HF_TOKEN_1!,
      model: "Qwen-3.5-7B",
      tier: "prime",
      maxTokens: 4096,
      supportsVision: false,
      supportsStreaming: false,
      rateLimit: 50,
      priority: 8,
    },
    {
      id: "cerebras-prime",
      name: "Cerebras",
      endpoint: "https://api.cerebras.ai/v1/chat/completions",
      apiKey: process.env.CEREBRAS_KEY!,
      model: "qwen-3-32b",
      tier: "prime",
      maxTokens: 4096,
      supportsVision: false,
      supportsStreaming: true,
      rateLimit: 30,
      priority: 15,
    },
  ],
  apex: [
    {
      id: "fireworks-apex",
      name: "Fireworks Qwen",
      endpoint: "https://api.fireworks.ai/inference/v1/chat/completions",
      apiKey: process.env.FIREWORKS_KEY!,
      model: "accounts/fireworks/models/qwen2p5-72b-instruct",
      tier: "apex",
      maxTokens: 8192,
      supportsVision: false,
      supportsStreaming: true,
      rateLimit: 100,
      priority: 1,
    },
    {
      id: "siliconflow-apex",
      name: "SiliconFlow Apex",
      endpoint: "https://api.siliconflow.cn/v1/chat/completions",
      apiKey: process.env.SILICONFLOW_KEY_1!,
      model: "Qwen/Qwen2.5-32B-Instruct",
      tier: "apex",
      maxTokens: 8192,
      supportsVision: false,
      supportsStreaming: true,
      rateLimit: 100,
      priority: 2,
    },
    {
      id: "hf-apex-dynamic",
      name: "HF Apex",
      endpoint: "dynamic",
      apiKey: process.env.HF_TOKEN_APEX_1!,
      model: "Qwen-3.5-9B",
      tier: "apex",
      maxTokens: 8192,
      supportsVision: false,
      supportsStreaming: false,
      rateLimit: 30,
      priority: 5,
    },
  ],
}
