'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import {
  ArrowLeft, Plus, Package, ExternalLink, Globe, Clock,
  Cpu, Code2, Folder, Search, Grid3X3, List
} from 'lucide-react'
import { cn } from '@/lib/utils'

interface Project {
  id: string
  name: string
  description: string
  template: string
  files: Record<string, string>
  stackblitzUrl?: string
  createdAt: Date
  updatedAt: Date
}

function OpenInStackBlitz({ files, name }: { files: Record<string, string>; name: string }) {
  const handleOpen = () => {
    const form = document.createElement('form')
    form.method = 'POST'
    form.action = 'https://stackblitz.com/run'
    form.target = '_blank'
    form.style.display = 'none'

    const addField = (n: string, v: string) => {
      const el = document.createElement('input')
      el.type = 'hidden'
      el.name = n
      el.value = v
      form.appendChild(el)
    }

    addField('project[title]', name)
    addField('project[description]', 'Generated by Zero AI App Factory')
    addField('project[template]', 'html')

    Object.entries(files).forEach(([path, content]) => {
      addField(`project[files][${path}]`, content)
    })

    document.body.appendChild(form)
    form.submit()
    document.body.removeChild(form)
  }

  return (
    <button
      onClick={handleOpen}
      className="flex items-center gap-1.5 rounded-lg bg-[#1389FD]/10 border border-[#1389FD]/20 px-3 py-1.5 text-xs font-semibold text-[#1389FD] hover:bg-[#1389FD]/20 transition-all"
      title="Open in StackBlitz → Deploy & live preview"
    >
      <Globe className="h-3.5 w-3.5" />
      StackBlitz
    </button>
  )
}

const TEMPLATE_COLORS: Record<string, string> = {
  landing:     'from-violet-500/20 to-purple-500/10',
  dashboard:   'from-blue-500/20 to-cyan-500/10',
  tool:        'from-emerald-500/20 to-teal-500/10',
  game:        'from-orange-500/20 to-amber-500/10',
  'ai-chat':   'from-pink-500/20 to-rose-500/10',
  portfolio:   'from-slate-500/20 to-gray-500/10',
  'saas-starter': 'from-indigo-500/20 to-blue-500/10',
  ecommerce:   'from-green-500/20 to-emerald-500/10',
}

const TEMPLATE_ICONS: Record<string, string> = {
  landing: '🚀', dashboard: '📊', tool: '⚙️', game: '🎮',
  'ai-chat': '🤖', portfolio: '💼', 'saas-starter': '☁️', ecommerce: '🛒',
}

function ProjectCard({ project, view }: { project: Project; view: 'grid' | 'list' }) {
  const gradient = TEMPLATE_COLORS[project.template] || 'from-zero-300/20 to-zero-100/10'
  const icon = TEMPLATE_ICONS[project.template] || '📦'
  const fileCount = Object.keys(project.files).length

  if (view === 'list') {
    return (
      <div className="flex items-center justify-between gap-4 rounded-2xl border border-border bg-bg-1 p-4 hover:border-border-hover hover:bg-bg-2 transition-all group">
        <div className="flex items-center gap-4 min-w-0">
          <div className={cn('h-10 w-10 rounded-xl bg-gradient-to-br flex items-center justify-center text-xl shrink-0', gradient)}>
            {icon}
          </div>
          <div className="min-w-0">
            <h3 className="font-semibold text-text-1 truncate">{project.name}</h3>
            <p className="text-xs text-text-3 truncate mt-0.5">{project.description}</p>
          </div>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <span className="hidden sm:flex text-xs text-text-3 items-center gap-1">
            <Code2 className="h-3.5 w-3.5" /> {fileCount} files
          </span>
          <span className="hidden sm:flex text-xs text-text-3 items-center gap-1">
            <Clock className="h-3.5 w-3.5" /> {new Date(project.createdAt).toLocaleDateString()}
          </span>
          <OpenInStackBlitz files={project.files} name={project.name} />
          <Link href={`/artifacts?app=${project.id}`}
            className="rounded-lg bg-bg-2 border border-border px-3 py-1.5 text-xs text-text-2 hover:text-text-1 transition-all">
            Files →
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="group rounded-2xl border border-border bg-bg-1 overflow-hidden hover:border-border-hover transition-all hover:-translate-y-0.5">
      {/* Preview banner */}
      <div className={cn('h-32 bg-gradient-to-br flex items-center justify-center relative overflow-hidden', gradient)}>
        <span className="text-5xl select-none">{icon}</span>
        <div className="absolute inset-0 bg-gradient-to-t from-bg-1/60 to-transparent" />
        <div className="absolute bottom-2 right-2 flex items-center gap-1.5">
          <span className="text-[10px] bg-bg-0/70 backdrop-blur-sm text-text-2 px-2 py-0.5 rounded-full border border-border/50">
            {project.template}
          </span>
        </div>
      </div>

      {/* Info */}
      <div className="p-4">
        <h3 className="font-semibold text-text-1 truncate mb-1">{project.name}</h3>
        <p className="text-xs text-text-3 line-clamp-2 mb-3">{project.description}</p>

        <div className="flex items-center gap-2 text-[10px] text-text-3 mb-4">
          <span className="flex items-center gap-1"><Code2 className="h-3 w-3" />{fileCount} files</span>
          <span>·</span>
          <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{new Date(project.createdAt).toLocaleDateString()}</span>
        </div>

        <div className="flex items-center gap-2">
          <OpenInStackBlitz files={project.files} name={project.name} />
          <Link href="/artifacts"
            className="flex-1 text-center rounded-xl border border-border bg-bg-2 px-3 py-1.5 text-xs text-text-2 hover:text-text-1 transition-all">
            View Files
          </Link>
        </div>
      </div>
    </div>
  )
}

export default function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [view, setView] = useState<'grid' | 'list'>('grid')

  useEffect(() => {
    const loaded: Project[] = []

    // Load app factory projects from chat localStorage
    try {
      const keys = Object.keys(localStorage)
      for (const key of keys) {
        if (!key.startsWith('chat_')) continue
        const raw = localStorage.getItem(key)
        if (!raw) continue

        const messages: any[] = JSON.parse(raw)
        for (const msg of messages) {
          if (msg.hasAppFactory && msg.appFactoryFiles) {
            loaded.push({
              id: msg.id || `proj_${Date.now()}_${Math.random()}`,
              name: (msg.appFactoryDescription || msg.content || 'Untitled App').slice(0, 60),
              description: msg.content?.slice(0, 120) || '',
              template: msg.appFactoryTemplate || 'landing',
              files: msg.appFactoryFiles,
              stackblitzUrl: msg.appFactoryUrl,
              createdAt: new Date(msg.createdAt || Date.now()),
              updatedAt: new Date(msg.createdAt || Date.now()),
            })
          }
        }
      }

      // Also check dedicated projects store
      const projRaw = localStorage.getItem('zero_projects')
      if (projRaw) {
        const stored: Project[] = JSON.parse(projRaw)
        loaded.push(...stored.map(p => ({ ...p, createdAt: new Date(p.createdAt), updatedAt: new Date(p.updatedAt) })))
      }
    } catch (e) {
      console.error('Projects load failed', e)
    }

    // Deduplicate by id, sort newest first
    const deduped = Array.from(new Map(loaded.map(p => [p.id, p])).values())
    deduped.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
    setProjects(deduped)
    setLoading(false)
  }, [])

  const filtered = projects.filter(p =>
    search === '' ||
    p.name.toLowerCase().includes(search.toLowerCase()) ||
    p.description.toLowerCase().includes(search.toLowerCase()) ||
    p.template.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div className="min-h-screen bg-bg-0">
      <header className="sticky top-0 z-10 border-b border-border bg-bg-1/80 backdrop-blur-md">
        <div className="mx-auto flex max-w-6xl items-center gap-4 px-4 py-4">
          <Link href="/chat" className="text-text-2 hover:text-text-1 transition-colors">
            <ArrowLeft className="h-5 w-5" />
          </Link>
          <div className="flex-1">
            <h1 className="text-lg font-semibold text-text-1">Projects</h1>
            <p className="text-xs text-text-3">{projects.length} app{projects.length !== 1 ? 's' : ''} generated</p>
          </div>
          <Link href="/app-factory"
            className="flex items-center gap-2 rounded-xl bg-zero-300 px-4 py-2 text-sm font-semibold text-bg-0 hover:bg-zero-400 transition-all hover:scale-105">
            <Plus className="h-4 w-4" /> New App
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-4 py-8">
        {/* Search + view toggle */}
        <div className="flex items-center gap-3 mb-8">
          <div className="relative flex-1 max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-text-3" />
            <input
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search projects…"
              className="w-full rounded-xl border border-border bg-bg-1 pl-10 pr-4 py-2.5 text-sm text-text-1 placeholder-text-3 focus:outline-none focus:border-zero-300 transition-colors"
            />
          </div>
          <div className="flex items-center gap-1 rounded-xl border border-border bg-bg-1 p-1">
            <button onClick={() => setView('grid')}
              className={cn('rounded-lg p-2 transition-all', view === 'grid' ? 'bg-bg-3 text-text-1' : 'text-text-3 hover:text-text-2')}>
              <Grid3X3 className="h-4 w-4" />
            </button>
            <button onClick={() => setView('list')}
              className={cn('rounded-lg p-2 transition-all', view === 'list' ? 'bg-bg-3 text-text-1' : 'text-text-3 hover:text-text-2')}>
              <List className="h-4 w-4" />
            </button>
          </div>
        </div>

        {loading && (
          <div className="flex flex-col items-center justify-center py-24 gap-4">
            <div className="h-8 w-8 rounded-full border-2 border-zero-300 border-t-transparent animate-spin" />
            <p className="text-sm text-text-3">Loading projects…</p>
          </div>
        )}

        {!loading && filtered.length === 0 && (
          <div className="flex flex-col items-center justify-center py-24 gap-6 text-center">
            <div className="h-20 w-20 rounded-3xl bg-bg-1 border border-border flex items-center justify-center">
              <Folder className="h-10 w-10 text-text-3" />
            </div>
            <div>
              <p className="text-xl font-semibold text-text-1 mb-2">
                {search ? 'No matching projects' : 'No projects yet'}
              </p>
              <p className="text-sm text-text-3 max-w-sm">
                {search
                  ? `No projects match "${search}". Try a different search.`
                  : 'Build your first app with the App Factory. Describe any app and get live code in seconds.'}
              </p>
            </div>
            {!search && (
              <Link href="/app-factory"
                className="flex items-center gap-2 rounded-2xl bg-zero-300 px-6 py-3 font-semibold text-bg-0 hover:bg-zero-400 transition-all hover:scale-105">
                <Package className="h-5 w-5" /> Launch App Factory
              </Link>
            )}
          </div>
        )}

        {view === 'grid' ? (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {filtered.map(project => (
              <ProjectCard key={project.id} project={project} view="grid" />
            ))}
          </div>
        ) : (
          <div className="space-y-3">
            {filtered.map(project => (
              <ProjectCard key={project.id} project={project} view="list" />
            ))}
          </div>
        )}
      </main>
    </div>
  )
}
