'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import {
  ArrowLeft, ExternalLink, Code2, Image, Package,
  Folder, Clock, Globe, Download, Copy, Check, Filter
} from 'lucide-react'
import { cn } from '@/lib/utils'

type ArtifactType = 'code' | 'image' | 'app' | 'all'

interface Artifact {
  id: string
  type: 'code' | 'image' | 'app'
  title: string
  description?: string
  content?: string         // code content
  language?: string        // for code
  imageUrl?: string        // for images
  stackblitzUrl?: string   // for apps
  files?: Record<string, string>  // for apps
  template?: string
  createdAt: Date
}

function OpenInStackBlitz({ files }: { files: Record<string, string> }) {
  const handleOpen = () => {
    // Use StackBlitz SDK approach — post a form dynamically
    const form = document.createElement('form')
    form.method = 'POST'
    form.action = 'https://stackblitz.com/run'
    form.target = '_blank'
    form.style.display = 'none'

    const addField = (name: string, value: string) => {
      const input = document.createElement('input')
      input.type = 'hidden'
      input.name = name
      input.value = value
      form.appendChild(input)
    }

    addField('project[title]', 'Zero AI App')
    addField('project[description]', 'Generated by Zero AI App Factory')
    addField('project[template]', 'html')

    Object.entries(files).forEach(([path, content]) => {
      addField(`project[files][${path}]`, content)
    })

    document.body.appendChild(form)
    form.submit()
    document.body.removeChild(form)
  }

  return (
    <button
      onClick={handleOpen}
      className="flex items-center gap-1.5 rounded-lg bg-[#1389FD]/10 border border-[#1389FD]/20 px-3 py-1.5 text-xs font-semibold text-[#1389FD] hover:bg-[#1389FD]/20 transition-all hover:scale-105"
    >
      <Globe className="h-3.5 w-3.5" />
      Deploy on StackBlitz
    </button>
  )
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  const copy = () => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <button onClick={copy}
      className="flex items-center gap-1 rounded-lg bg-bg-2 px-2.5 py-1.5 text-xs text-text-2 hover:text-text-1 transition-all"
    >
      {copied ? <Check className="h-3.5 w-3.5 text-green-400" /> : <Copy className="h-3.5 w-3.5" />}
      {copied ? 'Copied' : 'Copy'}
    </button>
  )
}

function ArtifactCard({ artifact }: { artifact: Artifact }) {
  const [expanded, setExpanded] = useState(false)

  return (
    <div className="group rounded-2xl border border-border bg-bg-1 overflow-hidden hover:border-border-hover transition-all">
      {/* Header */}
      <div className="flex items-start justify-between gap-3 p-4">
        <div className="flex items-center gap-3 min-w-0">
          <div className={cn(
            'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl',
            artifact.type === 'code'  ? 'bg-violet-500/15 text-violet-400'
            : artifact.type === 'image' ? 'bg-pink-500/15 text-pink-400'
            : 'bg-blue-500/15 text-blue-400'
          )}>
            {artifact.type === 'code'  ? <Code2 className="h-5 w-5" />
             : artifact.type === 'image' ? <Image className="h-5 w-5" />
             : <Package className="h-5 w-5" />}
          </div>
          <div className="min-w-0">
            <h3 className="font-semibold text-text-1 truncate">{artifact.title}</h3>
            {artifact.description && (
              <p className="text-xs text-text-3 mt-0.5 truncate">{artifact.description}</p>
            )}
            <div className="flex items-center gap-2 mt-1">
              {artifact.language && (
                <span className="text-[10px] font-mono bg-bg-3 text-text-3 px-1.5 py-0.5 rounded">{artifact.language}</span>
              )}
              {artifact.template && (
                <span className="text-[10px] bg-blue-500/10 text-blue-400 px-1.5 py-0.5 rounded">{artifact.template}</span>
              )}
              <span className="text-[10px] text-text-3 flex items-center gap-1">
                <Clock className="h-3 w-3" />
                {new Date(artifact.createdAt).toLocaleDateString()}
              </span>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2 shrink-0">
          {artifact.type === 'app' && artifact.files && (
            <OpenInStackBlitz files={artifact.files} />
          )}
          {artifact.type === 'code' && artifact.content && (
            <CopyButton text={artifact.content} />
          )}
          {artifact.type === 'image' && artifact.imageUrl && (
            <a href={artifact.imageUrl} target="_blank" rel="noopener"
              className="flex items-center gap-1 rounded-lg bg-bg-2 px-2.5 py-1.5 text-xs text-text-2 hover:text-text-1 transition-all"
            >
              <ExternalLink className="h-3.5 w-3.5" /> Open
            </a>
          )}
          <button onClick={() => setExpanded(!expanded)}
            className="rounded-lg bg-bg-2 px-2.5 py-1.5 text-xs text-text-2 hover:text-text-1 transition-all"
          >
            {expanded ? 'Hide' : 'Preview'}
          </button>
        </div>
      </div>

      {/* Expanded content */}
      {expanded && (
        <div className="border-t border-border">
          {artifact.type === 'image' && artifact.imageUrl && (
            <div className="p-4">
              <img src={artifact.imageUrl} alt={artifact.title}
                className="max-h-80 rounded-xl object-contain mx-auto" />
            </div>
          )}

          {artifact.type === 'code' && artifact.content && (
            <div className="relative">
              <pre className="overflow-x-auto p-4 text-xs text-text-2 font-mono max-h-80 bg-bg-0 leading-relaxed">
                <code>{artifact.content}</code>
              </pre>
            </div>
          )}

          {artifact.type === 'app' && artifact.files && (
            <div className="p-4 space-y-3">
              <div className="flex items-center justify-between mb-2">
                <p className="text-xs font-semibold text-text-2 uppercase tracking-widest">Generated Files</p>
                <OpenInStackBlitz files={artifact.files} />
              </div>
              {Object.entries(artifact.files).map(([filename, content]) => (
                <div key={filename} className="rounded-xl border border-border/50 overflow-hidden">
                  <div className="flex items-center justify-between bg-bg-2 px-3 py-2">
                    <span className="text-xs font-mono text-text-2">{filename}</span>
                    <CopyButton text={content} />
                  </div>
                  <pre className="overflow-x-auto p-3 text-xs font-mono text-text-3 max-h-48 bg-bg-0">
                    {content.slice(0, 2000)}{content.length > 2000 ? '\n... (truncated)' : ''}
                  </pre>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

export default function ArtifactsPage() {
  const [artifacts, setArtifacts] = useState<Artifact[]>([])
  const [filter, setFilter] = useState<ArtifactType>('all')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const loaded: Artifact[] = []

    // Load from chat history in localStorage
    try {
      const keys = Object.keys(localStorage)
      for (const key of keys) {
        if (!key.startsWith('chat_')) continue
        const raw = localStorage.getItem(key)
        if (!raw) continue
        const messages = JSON.parse(raw) as any[]

        for (const msg of messages) {
          // Images
          if (msg.imageUrl) {
            loaded.push({
              id: `img_${msg.id}`,
              type: 'image',
              title: msg.content?.slice(0, 60) || 'Generated Image',
              imageUrl: msg.imageUrl,
              createdAt: new Date(msg.createdAt || Date.now()),
            })
          }

          // App Factory apps
          if (msg.hasAppFactory && msg.appFactoryFiles) {
            loaded.push({
              id: `app_${msg.id}`,
              type: 'app',
              title: msg.appFactoryDescription || msg.content?.slice(0, 60) || 'Generated App',
              description: `Template: ${msg.appFactoryTemplate || 'custom'}`,
              files: msg.appFactoryFiles,
              template: msg.appFactoryTemplate,
              stackblitzUrl: msg.appFactoryUrl,
              createdAt: new Date(msg.createdAt || Date.now()),
            })
          }

          // Code blocks in assistant messages
          if (msg.role === 'assistant' && msg.content) {
            const codeRe = /```(\w+)?\n([\s\S]*?)```/g
            let match
            let codeIdx = 0
            while ((match = codeRe.exec(msg.content)) !== null) {
              const [, lang, code] = match
              if (code.length > 50) {
                loaded.push({
                  id: `code_${msg.id}_${codeIdx++}`,
                  type: 'code',
                  title: `${lang || 'Code'} snippet`,
                  description: msg.content.slice(0, 60),
                  content: code.trim(),
                  language: lang || 'text',
                  createdAt: new Date(msg.createdAt || Date.now()),
                })
              }
            }
          }
        }
      }
    } catch (e) {
      console.error('Failed to load artifacts from localStorage', e)
    }

    // Sort newest first
    loaded.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    setArtifacts(loaded)
    setLoading(false)
  }, [])

  const filtered = filter === 'all' ? artifacts : artifacts.filter(a => a.type === filter)

  const counts = {
    all:   artifacts.length,
    code:  artifacts.filter(a => a.type === 'code').length,
    image: artifacts.filter(a => a.type === 'image').length,
    app:   artifacts.filter(a => a.type === 'app').length,
  }

  return (
    <div className="min-h-screen bg-bg-0">
      <header className="sticky top-0 z-10 border-b border-border bg-bg-1/80 backdrop-blur-md">
        <div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-4 py-4">
          <div className="flex items-center gap-4">
            <Link href="/chat" className="text-text-2 hover:text-text-1 transition-colors">
              <ArrowLeft className="h-5 w-5" />
            </Link>
            <div>
              <h1 className="text-lg font-semibold text-text-1">Artifacts</h1>
              <p className="text-xs text-text-3">{counts.all} total · Code, Images, Apps</p>
            </div>
          </div>
          <Link href="/app-factory"
            className="flex items-center gap-2 rounded-xl bg-zero-300 px-4 py-2 text-sm font-semibold text-bg-0 hover:bg-zero-400 transition-all hover:scale-105">
            <Package className="h-4 w-4" /> New App
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-8">
        {/* Filter tabs */}
        <div className="flex items-center gap-2 mb-8 flex-wrap">
          {([
            { key: 'all',   label: 'All',    icon: Filter },
            { key: 'app',   label: 'Apps',   icon: Package },
            { key: 'code',  label: 'Code',   icon: Code2 },
            { key: 'image', label: 'Images', icon: Image },
          ] as const).map(({ key, label, icon: Icon }) => (
            <button key={key} onClick={() => setFilter(key as ArtifactType)}
              className={cn(
                'flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-all',
                filter === key
                  ? 'bg-zero-300 text-bg-0 shadow-lg shadow-zero-300/20'
                  : 'bg-bg-1 border border-border text-text-2 hover:text-text-1 hover:bg-bg-2'
              )}
            >
              <Icon className="h-4 w-4" />
              {label}
              <span className={cn(
                'text-xs rounded-full px-1.5 py-0.5 font-semibold min-w-[20px] text-center',
                filter === key ? 'bg-bg-0/30' : 'bg-bg-3 text-text-3'
              )}>
                {counts[key]}
              </span>
            </button>
          ))}
        </div>

        {loading && (
          <div className="flex flex-col items-center justify-center py-24 gap-4">
            <div className="h-8 w-8 rounded-full border-2 border-zero-300 border-t-transparent animate-spin" />
            <p className="text-sm text-text-3">Loading artifacts…</p>
          </div>
        )}

        {!loading && filtered.length === 0 && (
          <div className="flex flex-col items-center justify-center py-24 gap-4 text-center">
            <div className="h-16 w-16 rounded-2xl bg-bg-1 border border-border flex items-center justify-center">
              <Folder className="h-8 w-8 text-text-3" />
            </div>
            <div>
              <p className="font-semibold text-text-1">No artifacts yet</p>
              <p className="text-sm text-text-3 mt-1">
                {filter === 'app' ? 'Build an app in the App Factory to see it here'
                 : filter === 'image' ? 'Generate images in chat to see them here'
                 : filter === 'code' ? 'Code blocks from chat will appear here'
                 : 'Start chatting to generate artifacts'}
              </p>
            </div>
            <Link href="/chat"
              className="rounded-xl bg-bg-1 border border-border px-5 py-2.5 text-sm text-text-2 hover:text-text-1 hover:bg-bg-2 transition-all">
              Start chatting →
            </Link>
          </div>
        )}

        <div className="space-y-4">
          {filtered.map(artifact => (
            <ArtifactCard key={artifact.id} artifact={artifact} />
          ))}
        </div>
      </main>
    </div>
  )
}
